### ISSUE TITLE
Capital mode - false positive after "e.g."

### ISSUE THREAD

**Issue by johananl** [tetafro/godot#21]
The following causes a false positive:

```go
// The client uses processName to identify itself to the cluster (e.g. when logging events).
```

The linter complains about `when`, most likely because it is confused by `e.g.`.

godot version: `v1.4.4`

Config:

```yaml
linters-settings:
  godot:
    capital: true
```
